[tox]
envlist =
    py{311,312,313,314}-django52
    lint

[testenv:lint]
deps =
    pipenv
    flake8
    black
basepython = python3.11
commands =
    pipenv sync --dev
    flake8 {toxinidir}/oidc
    black -v {toxinidir}/oidc --check -t py311
    isort -c -v {toxinidir}/oidc

[testenv]
deps =
    pipenv
basepython =
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14
commands =
    django52: pip install Django>=5.2,<6
    pipenv sync --dev
    python manage.py test {toxinidir}/tests
